controllers:
    resource: '../src/Controller/'
    type: 'annotation'

salaire:
    path: /salaire
    controller: App\Controller\CalcuSalaireController::calculSalaire


api_login_check:
    path: /api/login_check